#!/bin/bash

set -e
set -u

SRC=$1
DEST=$2
DPI=$3

export DBUS_SESSION_BUS_ADDRESS=/dev/null

mkdir -p "$DEST"

function ink()
{
    find $SRC -name "*.svg" -print | \
    while read F; do
    {
        NAME=${F##*/}
        NAME=${NAME%.svg}

        SVG="$SRC/$NAME.svg"
        PNG="$DEST/$NAME.png"

        if [[ "$SVG" -nt "$PNG" ]]; then
            echo "$SVG --export-png=$PNG --export-dpi=$DPI"
            echo ".. svg->png $PNG" 1>&2
        fi
    }; done | \
        inkscape --shell > /dev/null 2>/dev/null
}

ink 2>&1
